# Brew Bundle Brewfile Tips
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f

# tap "homebrew/core"
# tap "homebrew/bundle"
tap "homebrew/cask"
tap "buo/cask-upgrade" # Allow to upgrade casks

# Brew

# TODO: Linux apps
brew "asdf"
brew "awscli"
brew "bat" # Better cat
brew "direnv"
brew "fzf" # Better shell history
brew "gh" # Github CLI; checks action results from CLI
brew "git"
brew "git-delta" # Better git diff
brew "git-lfs"
brew "jordanbaird-ice" # Show menu bar items hidden by notch
brew "mas" # Allow to install Mac App Store apps
brew "opentofu"
brew "ripgrep" # Better ag
brew "stats" # Replace iStats
brew "tlrc" # Better manpages
brew "vim"
brew "zoxide"
brew "zsh" # Upgrade zsh from stock macos

# Casks
# cask "monitorcontrol"
cask "1password"
cask "aldente"
cask "chatgpt"
cask "cold-turkey"
cask "cursor"
cask "dropbox"
cask "flux"
cask "google-chrome"
cask "google-cloud-sdk" # Google Cloud CLI
cask "iterm2"
cask "mullvadvpn"
cask "notion"
cask "orbstack" # Better docker
cask "postico" # Postgresql client
cask "raycast"
cask "rocket" # Slack-style emojis in every app
cask "signal"
cask "slack"
cask "spotify"
cask "todoist"
cask "zoom"

# Mac App Store
mas "Coin Tick", id: 1141688067
mas "Magnet", id: 441258766
mas "MeetingBar", id: 1532419400
mas "Velja", id: 1607635845 # Rules to open correct chrome profile based on url