require 'rake'

task :brew do
  puts "Installing homebrew..."
  sh '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  sh 'echo \'eval "$(/opt/homebrew/bin/brew shellenv)"\' >> ~/.zprofile'
  sh 'eval "$(/opt/homebrew/bin/brew shellenv)"'
  puts "Installing brew bundle..."
  sh '/opt/homebrew/bin/brew bundle'
end

task :osx do
  # Used plistwatch to find the keys
  # asdf plugin add golfing
  # asdf install golang latest
  # go install github.com/catilac/plistwatch@latest
  # .asdf/installs/golang/1.20.2/packages/bin/plistwatch

  #  ## Dock
  # Dock size
  sh "defaults write com.apple.dock tilesize '34'"
  # Dock magnification
  sh "defaults write com.apple.dock largesize '64'"
  # Dock on left side of screen
  sh "defaults write com.apple.dock orientation 'left'"
  # Scale effect vs. genie effect for window minimization
  sh "defaults write com.apple.dock mineffect 'scale'"
  # Get rid of the delay when showing and hiding the Dock
  sh "defaults write com.apple.dock autohide-time-modifier -float 0.20"

  ## Spaces
  # Re-arrange space based on most recent use
  sh "defaults write com.apple.dock mru-spaces '0'"

  ## Hotcorners
  # sh "defaults write com.apple.dock wvous-tl-corner -int 3"
  # sh "defaults write com.apple.dock wvous-bl-corner -int 4"
  # sh "defaults write com.apple.dock wvous-tr-corner -int 2"
  # Top-right corner -> Application Windows
  sh "defaults write com.apple.dock wvous-tr-modifier '0'"
  sh "defaults write com.apple.dock wvous-tr-corner '3'"
  # Bottom-rih cornr -> Application Windows
  sh "defaults write com.apple.dock wvous-br-modifier '0'"
  sh "defaults write com.apple.dock wvous-br-corner '3'"
  # Top-left oner - Mission Control
  sh "defaults write com.apple.dock wvous-tl-modifier '0'"
  sh "defaults write com.apple.dock wvous-tl-corner '2'"
  # Bottom-letcorne -> Desktop
  sh "defaults write com.apple.dock wvous-bl-corner '4'"
  sh "defaults write com.apple.dock wvous-bl-modifier '0'"

  ## Trackpad
  # sh "defaults write com.apple.driver.AppleBluetoothMultitouctrackpad Clicking -int 1"

  ## Keyboard
  # sh "defaults write NSGlobalDomain KeyRepeat -int 1"
  # sh "defaults write NSGlobalDomain InitialKeyRepeat -int 10"

  ## Finder
  # Show file extensions

  ## Misc
  # Disable Window Animation
  sh "defaults write com.apple.dock expose-animation-duration -float 0"
  # If you use multiple monitors, and you're frustrated with the cmd-tab app switcher
  # only appearing on the last monitor you touched the dock,
  # this will make it show up on all monitors.
  #sh "defaults write com.apple.Dock appswitcher-all-displays -bool true"

  # Remapping capslock to escape is manual, nocommand

  sh "killall Dock"
  sh "killall Finder"

  puts "IMPORTANT: Restart for all changes to take effect"
end

task :symlinks do
  sh "ln -sf #{__dir__.chomp('/scripts')}/.gitconfig ~/.gitconfig"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.ssh ~/"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.tmux.conf ~/.tmux.conf"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.tool-versions ~/.tool-versions"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.vimrc ~/.vimrc"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.zimrc ~/.zimrc"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.zprofile ~/.zprofile"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.zshrc ~/.zshrc"
  sh "ln -sf #{__dir__.chomp('/scripts')}/.psqlrc ~/.psqlrc"
end

# task :setup => [:brew, :osx, :symlinks]

