#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Disable autocorrect
unsetopt CORRECT

# Editors
alias v='vim'
alias s='subl .'
alias c='code .'

# Git
alias m='smerge .'
alias gst='git status'
alias com='git commit'
alias push='git push'
alias gsb='git status -s'
alias gb='git branch'
alias gut='git'
alias gpm='git checkout -q main && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base main $branch) && [[ $(git cherry main $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done'
alias wip='com -S -n -m "WIP"'
alias tst='tig status'

# Misc aliases
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='lt'

# Turn off the special expansion of zsh for rake (hard brackets issue)
alias rake='noglob rake'
alias be='bundle exec'

# Docker
alias compose='docker-compose'

# Tmux
alias tma='tmux attach -d -t'
alias tmn='tmux new -s'
alias tml='tmux list-sessions'
alias tmk='tmux kill-session -t'
alias tmr='tmux rename-session -t'
alias tmux='TERM=screen-256color-bce tmux'

alias sound.restart="sudo kill -9 `ps ax | grep 'coreaudio[a-z]' | awk '{print $1}'`"
alias bluetooth.restart="pgrep bluetooth | xargs sudo kill"
alias ui.restart="sudo killall -HUP WindowServer"

# Autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# asdf setup: used for managing ruby, node versions etc.
. /usr/local/opt/asdf/asdf.sh

eval "$(github-copilot-cli alias -- "$0")"
eval "$(direnv hook zsh)"

