notify = ["/Users/ben/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
cli_auth_credentials_store = "keyring"
model = "gpt-5.6-sol"
model_catalog_json = "/Users/ben/.codex/models_long_context.json"
model_reasoning_effort = "xhigh"
service_tier = "fast"
approvals_reviewer = "auto_review"

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/ben/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/ben/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[features]
hooks = true
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/ben/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/ben/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.901.22334"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/ben/.codex/plugins/cache/openai-bundled/browser/26.901.22334/scripts/browser-service.mjs"}'
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[desktop]
default-service-tier = "priority"
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
preventSleepWhileRunning = true
show-context-window-usage = true
selected-avatar-id = "custom:taroko"
git-branch-prefix = "ben/"
git-pull-request-merge-method = "squash"
open-link-in-target-preference = "in-app-browser"

[desktop.open-in-target-preferences]
global = "zed"

[projects."/Users/ben/Documents/assistant"]
trust_level = "trusted"

[projects."/Users/ben/Work/yc/code"]
trust_level = "trusted"

[projects."/Users/ben/conductor/repos/Quickstart"]
trust_level = "trusted"

[projects."/Users/ben/Library/Application Support/com.conductor.app/bin"]
trust_level = "trusted"

[projects."/Users/ben/Work/yc/paxel"]
trust_level = "trusted"

[projects."/Users/ben"]
trust_level = "trusted"

[projects."/Users/ben/Work/dotfiles"]
trust_level = "trusted"

[projects."/Users/ben/Documents/Codex/2026-07-29/test"]
trust_level = "trusted"

[projects."/Users/ben/Work/yc/infra"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/ben/Work/yc/etl"]
trust_level = "trusted"

[projects."/Users/ben/Work/yc/remote-development"]
trust_level = "trusted"

[projects."/Users/ben/.config/yc-remote-dev"]
trust_level = "trusted"

[tui]
status_line = ["model", "reasoning", "fast-mode", "project-name", "current-dir", "git-branch", "used-tokens", "context-used"]
status_line_use_colors = true
pet = "custom:taroko"

[tui.model_availability_nux]
"gpt-5.5" = 3
"gpt-5.6-sol" = 4

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "028a14b6eaa6d98dac2aae00764345ab9f244801ed8493d42b9af3be5575006e,f204d340535055781952b10ed396de20b842f00a19e430852f7e121ad1ce91f6"

[hooks.state]

[hooks.state."/Users/ben/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:a5eabd29c80d8d2402076537979a3b7bbebe1681bcfb7dbb8d89b63a91a1226b"
enabled = true

[hooks.state."/Users/ben/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:5b81e1345499eba3de0ad13306a39b2b5517afafa4503734e1a3576e31184de3"

[hooks.state."/Users/ben/.codex/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:a290a1760970aa5cb22f7d4c29ab2968fc641f89dcdbfc7b1f96a0aa886a1ca4"

[hooks.state."/Users/ben/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:77de7017dd8f09a27b6bee28ca7a0afe0be4587381902b1ae4b6b25e5bed2c64"

[hooks.state."/Users/ben/.codex/hooks.json:session_start:1:0"]
trusted_hash = "sha256:66526fb89912ae15163280efada8c96e2ff1e9c5734c256a9567ce31383370a8"

[hooks.state."/Users/ben/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:a603061d5816d1b453a5042f2f66322b476370732563ec4093893a50b5549eb6"

[hooks.state."/Users/ben/.codex/hooks.json:subagent_start:0:0"]
trusted_hash = "sha256:377e5007c271ca74e12b3c3466242720bcaa1d40bf9e35fdcd3b2634e47624c0"

[hooks.state."/Users/ben/.codex/hooks.json:subagent_stop:0:0"]
trusted_hash = "sha256:42cd43aa6ccfa412ac67c94a2da10e21fe3c625258add0b132f43437214cd40a"

[hooks.state."/Users/ben/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:a53a13c43f956d63be1a09daa0d23ba13c47992d6cfc8791c8dbbffab137f6da"
