#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

HISTSIZE=10000000
SAVEHIST=10000000
 
setopt EXTENDED_HISTORY # logs the start and elapsed time
setopt INC_APPEND_HISTORY   
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS     
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR='subl -w'
export BUNDLER_EDITOR='subl'
export VISUAL='vim'
export PAGER='less'

# RBENV
export RBENV_ROOT="$HOME/.rbenv"

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Turn off kqueue, tmux 2.2 is not doing it
export EVENT_NOKQUEUE=1

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
HOMEBREW=/usr/local/bin:/usr/local/sbin
NPM=/usr/local/share/npm/bin
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin

# activate vendor folder with Go 1.5
export GOPATH="$HOME/go"
export PATH=$HOMEBREW:$NPM:$GOPATH/bin:$PATH

# Default all heroku cli commands to be run in figurehr team
export HEROKU_ORGANIZATION=figurehr

# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi



export PATH="$HOME/.cargo/bin:$PATH"
export GPG_TTY=$(tty)
