#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load rbenv automatically
eval "$(rbenv init -)"

# Disable autocorrect
unsetopt CORRECT

# Editors
alias v='vim'
alias s='subl .'
alias c='code .'

# Git
alias m='smerge .'
alias gst='git status'
alias com='git commit'
alias push='git push'
alias gsb='git status -s'
alias gb='git branch'
alias gut='git'
alias gpm='git checkout master && comm -12 <(git branch | sed "s/ *//g") <(git remote prune origin | sed "s/^.*origin\///g") | xargs -L1 -J % git branch -D %'

# Misc aliases
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'

# Turn off the special expansion of zsh for rake (hard brackets issue)
alias rake='noglob rake'
alias be='bundle exec'
alias cdev='bundle exec cucumber --tags @dev'

# Docker
alias compose='docker-compose'

# Tmux
alias tma='tmux attach -d -t'
alias tmn='tmux new -s'
alias tml='tmux list-sessions'
alias tmk='tmux kill-session -t'
alias tmr='tmux rename-session -t'
alias tmux='TERM=screen-256color-bce tmux'

alias sound.restart="sudo kill -9 `ps ax | grep 'coreaudio[a-z]' | awk '{print $1}'`"

# Autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

